/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Eliel
 */
public class jFrTela extends javax.swing.JFrame {
    
    /**
     * Creates new form jFrTela
     */
    public jFrTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValue = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btAC = new javax.swing.JButton();
        btMoreLess = new javax.swing.JButton();
        btPercent = new javax.swing.JButton();
        btDivision = new javax.swing.JButton();
        btSeven = new javax.swing.JButton();
        btEigth = new javax.swing.JButton();
        btNine = new javax.swing.JButton();
        btMultiply = new javax.swing.JButton();
        btFour = new javax.swing.JButton();
        btFive = new javax.swing.JButton();
        btSix = new javax.swing.JButton();
        btSubtraction = new javax.swing.JButton();
        btOne = new javax.swing.JButton();
        btTwo = new javax.swing.JButton();
        btTree = new javax.swing.JButton();
        btSum = new javax.swing.JButton();
        btZero = new javax.swing.JButton();
        btDote = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        btIquals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        tfValue.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tfValue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfValue.setText("0.00");

        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        btAC.setText("AC");
        jPanel1.add(btAC);

        btMoreLess.setText("+/-");
        jPanel1.add(btMoreLess);

        btPercent.setText("%");
        btPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPercentActionPerformed(evt);
            }
        });
        jPanel1.add(btPercent);

        btDivision.setText("/");
        jPanel1.add(btDivision);

        btSeven.setText("7");
        jPanel1.add(btSeven);

        btEigth.setText("8");
        jPanel1.add(btEigth);

        btNine.setText("9");
        jPanel1.add(btNine);

        btMultiply.setText("*");
        btMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(btMultiply);

        btFour.setText("4");
        jPanel1.add(btFour);

        btFive.setText("5");
        jPanel1.add(btFive);

        btSix.setText("6");
        jPanel1.add(btSix);

        btSubtraction.setText("-");
        jPanel1.add(btSubtraction);

        btOne.setText("1");
        jPanel1.add(btOne);

        btTwo.setText("2");
        jPanel1.add(btTwo);

        btTree.setText("3");
        jPanel1.add(btTree);

        btSum.setText("+");
        jPanel1.add(btSum);

        btZero.setText("0");
        jPanel1.add(btZero);

        btDote.setText(".");
        jPanel1.add(btDote);

        btClose.setText("Fecahr");
        jPanel1.add(btClose);

        btIquals.setText("=");
        jPanel1.add(btIquals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(tfValue))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPercentActionPerformed

    private void btMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMultiplyActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAC;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDivision;
    private javax.swing.JButton btDote;
    private javax.swing.JButton btEigth;
    private javax.swing.JButton btFive;
    private javax.swing.JButton btFour;
    private javax.swing.JButton btIquals;
    private javax.swing.JButton btMoreLess;
    private javax.swing.JButton btMultiply;
    private javax.swing.JButton btNine;
    private javax.swing.JButton btOne;
    private javax.swing.JButton btPercent;
    private javax.swing.JButton btSeven;
    private javax.swing.JButton btSix;
    private javax.swing.JButton btSubtraction;
    private javax.swing.JButton btSum;
    private javax.swing.JButton btTree;
    private javax.swing.JButton btTwo;
    private javax.swing.JButton btZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfValue;
    // End of variables declaration//GEN-END:variables
}
